"""Rust/Cargo project management.

Provides helpers to:
- scaffold a Cargo crate from converted Rust sources,
- run ``cargo check`` on an isolated snippet (used by the compile-repair loop),
- run ``cargo build`` and ``cargo test`` on the full crate,
- run ``cargo clippy`` for idiomatic feedback.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
import textwrap
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Dict, List, Optional, Tuple

if TYPE_CHECKING:
    from fortran_to_rust.llm_client import LLMClient

_CARGO_TOML_TEMPLATE = """\
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{crate_name}"
path = "src/lib.rs"

[dev-dependencies]
# criterion is optional; uncomment to enable micro-benchmarks
# criterion = {{ version = "0.5", features = ["html_reports"] }}

[profile.release]
opt-level = 3
"""

_LIB_RS_HEADER = """\
//! Auto-generated Rust port of BLAS functions.
//!
//! Generated by the fortran-to-rust conversion pipeline.
//! Manual review is recommended before use in production.

#![allow(clippy::all, non_snake_case, unused_variables, dead_code)]
"""

_MAX_CRATE_REPAIR_ROUNDS = 3


def scaffold_crate(
    output_dir: Path,
    crate_name: str,
    rust_sources: Dict[str, str],  # function_name -> rust_source
) -> Path:
    """Create a Cargo crate at *output_dir/rust* and return its path."""
    crate_dir = output_dir / "rust"
    src_dir = crate_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Cargo.toml
    (crate_dir / "Cargo.toml").write_text(
        _CARGO_TOML_TEMPLATE.format(crate_name=crate_name)
    )

    # src/lib.rs — concatenate all converted routines
    lib_parts = [_LIB_RS_HEADER]
    mod_names: List[str] = []
    for fn_name, src in rust_sources.items():
        mod_name = fn_name.lower()
        mod_names.append(mod_name)
        mod_file = src_dir / f"{mod_name}.rs"
        mod_file.write_text(src)
        lib_parts.append(f"pub mod {mod_name};")
        # Flat re-export so accuracy examples can `use {crate_name}::*`
        lib_parts.append(f"pub use {mod_name}::*;")

    lib_parts.append("")  # trailing newline
    (src_dir / "lib.rs").write_text("\n".join(lib_parts))

    return crate_dir


def get_crate_lib_name(crate_dir: Path) -> str:
    """Return the lib name declared in *crate_dir*/Cargo.toml.

    Falls back to ``crate_dir.name`` if the file cannot be parsed so callers
    always get a usable string.  This is used to produce correct
    ``use <lib_name>::*;`` statements in generated Rust examples.
    """
    import re

    cargo_toml = crate_dir / "Cargo.toml"
    if cargo_toml.exists():
        content = cargo_toml.read_text()
        # Prefer the explicit [lib] name; fall back to [package] name.
        for section in (r"\[lib\]", r"\[package\]"):
            m = re.search(
                section + r"[^\[]*\bname\s*=\s*\"([^\"]+)\"",
                content,
                re.DOTALL,
            )
            if m:
                return m.group(1)
    return crate_dir.name


def quick_check(rust_source: str, work_dir: Path) -> Tuple[bool, str]:
    """Compile *rust_source* in a throw-away crate and return (ok, output).

    Used by the compile-repair loop so we don't need to build the whole crate.
    Returns (False, message) when ``cargo`` is not installed.
    """
    if not shutil.which("cargo"):
        return False, "cargo not found: install Rust from https://rustup.rs"
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        src_dir = tmp / "src"
        src_dir.mkdir()

        (tmp / "Cargo.toml").write_text(
            _CARGO_TOML_TEMPLATE.format(crate_name="check_snippet")
        )
        # Wrap in a lib — add a permissive header in case the LLM omitted it
        wrapped = _LIB_RS_HEADER + "\n" + rust_source
        (src_dir / "lib.rs").write_text(wrapped)

        try:
            result = subprocess.run(
                ["cargo", "check", "--message-format=short"],
                capture_output=True,
                text=True,
                cwd=tmpdir,
                timeout=60,
            )
        except FileNotFoundError:
            return False, "cargo not found: install Rust from https://rustup.rs"
        combined = (result.stdout + result.stderr).strip()
        return result.returncode == 0, combined


def build_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo build --release`` and return (ok, output).

    Returns (False, message) when ``cargo`` is not installed.
    """
    if not shutil.which("cargo"):
        return False, "cargo not found: install Rust from https://rustup.rs"
    try:
        result = subprocess.run(
            ["cargo", "build", "--release"],
            capture_output=True,
            text=True,
            cwd=crate_dir,
            timeout=120,
        )
    except FileNotFoundError:
        return False, "cargo not found: install Rust from https://rustup.rs"
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def test_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo test`` and return (ok, output).

    Returns (False, message) when ``cargo`` is not installed.
    """
    if not shutil.which("cargo"):
        return False, "cargo not found: install Rust from https://rustup.rs"
    try:
        result = subprocess.run(
            ["cargo", "test"],
            capture_output=True,
            text=True,
            cwd=crate_dir,
            timeout=120,
        )
    except FileNotFoundError:
        return False, "cargo not found: install Rust from https://rustup.rs"
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def clippy_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo clippy`` and return (ok, output).

    Returns (False, message) when ``cargo`` is not installed.
    """
    if not shutil.which("cargo"):
        return False, "cargo not found: install Rust from https://rustup.rs"
    try:
        result = subprocess.run(
            ["cargo", "clippy", "--", "-D", "warnings"],
            capture_output=True,
            text=True,
            cwd=crate_dir,
            timeout=60,
        )
    except FileNotFoundError:
        return False, "cargo not found: install Rust from https://rustup.rs"
    return result.returncode == 0, (result.stdout + result.stderr).strip()


# ---------------------------------------------------------------------------
# Helpers for crate-level LLM repair
# ---------------------------------------------------------------------------

def _strip_fences(text: str) -> str:
    """Remove markdown code fences that the LLM sometimes adds."""
    text = re.sub(r"^```(?:rust)?\s*\n?", "", text.strip(), flags=re.MULTILINE)
    text = re.sub(r"\n?```\s*$", "", text.strip(), flags=re.MULTILINE)
    return text.strip()


def _ensure_top_level_pub_fn(source: str, fn_name: str) -> str:
    """Ensure *fn_name* is declared ``pub`` at the top level.

    Handles two common LLM mistakes:
    1. Function is defined without ``pub`` → adds ``pub``.
    2. Function is already ``pub`` → no-op.
    """
    if re.search(
        rf"^pub\s+(?:unsafe\s+)?fn\s+{re.escape(fn_name)}\b", source, re.MULTILINE
    ):
        return source
    fixed, n = re.subn(
        rf"^fn\s+{re.escape(fn_name)}\b",
        f"pub fn {fn_name}",
        source,
        flags=re.MULTILINE,
    )
    return fixed if n > 0 else source


def _find_failing_modules(build_output: str) -> List[str]:
    """Parse cargo build output and return module names that have compile errors.

    Looks for lines containing ``src/<name>.rs:`` in the cargo diagnostic
    output (both the default and the ``--message-format=short`` styles).
    ``lib`` is excluded because it is auto-generated and not directly fixable
    by the per-function LLM repair loop.
    """
    seen: set = set()
    mods: List[str] = []
    for line in build_output.splitlines():
        m = re.search(r"src/(\w+)\.rs:", line)
        if m:
            mod = m.group(1)
            if mod != "lib" and mod not in seen:
                seen.add(mod)
                mods.append(mod)
    return mods


def _extract_module_errors(build_output: str, mod_name: str) -> str:
    """Extract error blocks that reference ``src/{mod_name}.rs``.

    Splits the output on blank lines to isolate diagnostic blocks, keeps
    those that mention the target file, and joins them back.  Falls back to
    the full output when no file-specific blocks are found.
    """
    blocks: List[str] = []
    current: List[str] = []
    for line in build_output.splitlines():
        if line.strip() == "":
            if current:
                block = "\n".join(current)
                if f"src/{mod_name}.rs" in block:
                    blocks.append(block)
                current = []
        else:
            current.append(line)
    if current:
        block = "\n".join(current)
        if f"src/{mod_name}.rs" in block:
            blocks.append(block)
    return "\n\n".join(blocks) if blocks else build_output


def repair_crate_with_llm(
    crate_dir: Path,
    rust_sources: Dict[str, str],
    llm: "LLMClient",
    progress_callback: Optional[Callable[[str], None]] = None,
    max_rounds: int = _MAX_CRATE_REPAIR_ROUNDS,
) -> Tuple[bool, str, Dict[str, str]]:
    """Attempt to fix a failing crate build with iterative LLM repair.

    For each repair round:
    1. Run ``cargo build --release``.
    2. Parse the output to identify which module files have errors.
    3. Call ``llm.repair_rust()`` for each failing module.
    4. Write the repaired sources back to disk.

    Repeats until the build passes or *max_rounds* is exhausted.

    Returns ``(build_ok, final_build_output, updated_rust_sources)``.
    The returned *updated_rust_sources* dict contains repaired source code
    for any modules that were modified, so callers can persist the fixes.
    """
    cb = progress_callback or (lambda msg: None)
    sources = dict(rust_sources)  # mutable copy
    src_dir = crate_dir / "src"

    if not shutil.which("cargo"):
        cb("  [yellow]cargo not found — skipping LLM repair loop.[/yellow]")
        return False, "cargo not found: install Rust from https://rustup.rs", sources

    for round_num in range(1, max_rounds + 1):
        ok, build_out = build_crate(crate_dir)
        if ok:
            return True, build_out, sources

        failing = _find_failing_modules(build_out)
        if not failing:
            cb(
                f"  [yellow]LLM repair round {round_num}: "
                "cannot identify failing modules in build output — stopping.[/yellow]"
            )
            return False, build_out, sources

        cb(
            f"  [yellow]Build failed (LLM repair round {round_num}/{max_rounds}) — "
            f"repairing {len(failing)} module(s): {', '.join(failing)}[/yellow]"
        )

        for mod_name in failing:
            mod_file = src_dir / f"{mod_name}.rs"
            current_source = sources.get(mod_name)
            if current_source is None:
                if mod_file.exists():
                    current_source = mod_file.read_text()
                else:
                    cb(f"    [dim]Skipping {mod_name}: source file not found.[/dim]")
                    continue

            module_errors = _extract_module_errors(build_out, mod_name)
            cb(f"    Repairing [bold cyan]{mod_name}[/bold cyan]…")
            try:
                repaired = _strip_fences(
                    llm.repair_rust(current_source, module_errors, mod_name)
                )
                repaired = _ensure_top_level_pub_fn(repaired, mod_name.lower())
                sources[mod_name] = repaired
                mod_file.write_text(repaired)
            except Exception as exc:
                cb(f"    [red]LLM repair failed for {mod_name}: {exc}[/red]")

    # Final build after all repair rounds are exhausted
    ok, build_out = build_crate(crate_dir)
    return ok, build_out, sources


def add_rust_tests(
    crate_dir: Path,
    test_cases: List[Dict],
) -> None:
    """Append generated #[test] functions to the crate's lib.rs.

    *test_cases* is a list of dicts with keys:
        name, fn_name, setup_code, call_code, assert_code
    """
    test_src = "\n\n#[cfg(test)]\nmod generated_tests {\n    use super::*;\n\n"
    for tc in test_cases:
        test_src += textwrap.dedent(f"""
    #[test]
    fn {tc['name']}() {{
        {tc['setup_code']}
        {tc['call_code']}
        {tc['assert_code']}
    }}
""")
    test_src += "}\n"

    lib_rs = crate_dir / "src" / "lib.rs"
    with lib_rs.open("a") as f:
        f.write(test_src)
