"""Rust/Cargo project management.

Provides helpers to:
- scaffold a Cargo crate from converted Rust sources,
- run ``cargo check`` on an isolated snippet (used by the compile-repair loop),
- run ``cargo build`` and ``cargo test`` on the full crate,
- run ``cargo clippy`` for idiomatic feedback.
"""

from __future__ import annotations

import subprocess
import tempfile
import textwrap
from pathlib import Path
from typing import Dict, List, Optional, Tuple

_CARGO_TOML_TEMPLATE = """\
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2021"

[lib]
name = "{crate_name}"
path = "src/lib.rs"

[dev-dependencies]
# criterion is optional; uncomment to enable micro-benchmarks
# criterion = {{ version = "0.5", features = ["html_reports"] }}

[profile.release]
opt-level = 3
"""

_LIB_RS_HEADER = """\
//! Auto-generated Rust port of BLAS functions.
//!
//! Generated by the fortran-to-rust conversion pipeline.
//! Manual review is recommended before use in production.

#![allow(clippy::all, non_snake_case, unused_variables, dead_code)]
"""


def scaffold_crate(
    output_dir: Path,
    crate_name: str,
    rust_sources: Dict[str, str],  # function_name -> rust_source
) -> Path:
    """Create a Cargo crate at *output_dir/rust/<crate_name>* and return its path."""
    crate_dir = output_dir / "rust" / crate_name
    src_dir = crate_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # Cargo.toml
    (crate_dir / "Cargo.toml").write_text(
        _CARGO_TOML_TEMPLATE.format(crate_name=crate_name)
    )

    # src/lib.rs — concatenate all converted routines
    lib_parts = [_LIB_RS_HEADER]
    mod_names: List[str] = []
    for fn_name, src in rust_sources.items():
        mod_name = fn_name.lower()
        mod_names.append(mod_name)
        mod_file = src_dir / f"{mod_name}.rs"
        mod_file.write_text(src)
        lib_parts.append(f"pub mod {mod_name};")

    lib_parts.append("")  # trailing newline
    (src_dir / "lib.rs").write_text("\n".join(lib_parts))

    return crate_dir


def quick_check(rust_source: str, work_dir: Path) -> Tuple[bool, str]:
    """Compile *rust_source* in a throw-away crate and return (ok, output).

    Used by the compile-repair loop so we don't need to build the whole crate.
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp = Path(tmpdir)
        src_dir = tmp / "src"
        src_dir.mkdir()

        (tmp / "Cargo.toml").write_text(
            _CARGO_TOML_TEMPLATE.format(crate_name="check_snippet")
        )
        # Wrap in a lib — add a permissive header in case the LLM omitted it
        wrapped = _LIB_RS_HEADER + "\n" + rust_source
        (src_dir / "lib.rs").write_text(wrapped)

        result = subprocess.run(
            ["cargo", "check", "--message-format=short"],
            capture_output=True,
            text=True,
            cwd=tmpdir,
            timeout=60,
        )
        combined = (result.stdout + result.stderr).strip()
        return result.returncode == 0, combined


def build_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo build --release`` and return (ok, output)."""
    result = subprocess.run(
        ["cargo", "build", "--release"],
        capture_output=True,
        text=True,
        cwd=crate_dir,
        timeout=120,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def test_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo test`` and return (ok, output)."""
    result = subprocess.run(
        ["cargo", "test"],
        capture_output=True,
        text=True,
        cwd=crate_dir,
        timeout=120,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def clippy_crate(crate_dir: Path) -> Tuple[bool, str]:
    """Run ``cargo clippy`` and return (ok, output)."""
    result = subprocess.run(
        ["cargo", "clippy", "--", "-D", "warnings"],
        capture_output=True,
        text=True,
        cwd=crate_dir,
        timeout=60,
    )
    return result.returncode == 0, (result.stdout + result.stderr).strip()


def add_rust_tests(
    crate_dir: Path,
    test_cases: List[Dict],
) -> None:
    """Append generated #[test] functions to the crate's lib.rs.

    *test_cases* is a list of dicts with keys:
        name, fn_name, setup_code, call_code, assert_code
    """
    test_src = "\n\n#[cfg(test)]\nmod generated_tests {\n    use super::*;\n\n"
    for tc in test_cases:
        test_src += textwrap.dedent(f"""
    #[test]
    fn {tc['name']}() {{
        {tc['setup_code']}
        {tc['call_code']}
        {tc['assert_code']}
    }}
""")
    test_src += "}\n"

    lib_rs = crate_dir / "src" / "lib.rs"
    with lib_rs.open("a") as f:
        f.write(test_src)
